#!/bin/bash

# Written By Woland

# Simple script to search the aur using the w3m browser

# Dependency:
#           w3m or any other cli browser

# https://github.com/wolandark
# https://github.com/wolandark/BASH_Scripts_For_Everyone

printf "Please type your search query\n " 
echo ''

read query 
# lynx https://archlinux.org/packages/?q=$query

w3m https://aur.archlinux.org/packages?O=0\&K=$query

