#!/bin/bash

# Written By Woland

# Sets wallpapers and changes them automatically

#Dependency:
#          feh
#          usage
#          change PIC_DIR to point to your wallpapers directory & run the script

# https://github.com/wolandark
# https://github.com/wolandark/BASH_Scripts_For_Everyone


#Default interval for changing the wallpapers
default_interval=120
#Wallpapers path
PIC_DIR="/home/woland/Pictures/HD/Landscape/"
PIC_LIST=("$PIC_DIR"*)

#Help msg
usage () {
    echo "Usage: $0 [-h] [-t interval] [-e] [-r reverse]"
    echo "Options:"
    echo "  -t interval    Set wallpaper change interval in seconds (default: $default_interval)"
    echo "  -e             Start from a wallpaper"
    echo "  -r             Set wallpaper in reverse order"
    echo "  -h             Display this help message"
}

#Main Function
set_pic(){
    if [ "$1" == "-r" ]; then
        for (( i=${#PIC_LIST[@]}-1; i>=0; i-- ))
        do
            feh --bg-scale "${PIC_LIST[i]}"
            sleep "${interval}"
        done
    elif [ "$1" == "-e" ]; then
        sorted_array=($(shuf -e "${PIC_LIST[@]}"))

        for i in "${sorted_array[@]}"
        do
            feh --bg-scale "$i"
            sleep "${interval}"
        done
    else
        # Loop through the array normally if no flag is given
        for i in "${PIC_LIST[@]}"
        do
            feh --bg-scale "$i"
            sleep "${interval}"
        done
    fi
}

#getops
while getopts ":ht:re" opt; do
    case ${opt} in
        h ) usage
            exit 0
            ;;
        t )
            interval=${OPTARG}
            ;;
        r )
            set_pic "-r"
            exit 0
            ;;
        e )
            set_pic "-e"
            exit 0
            ;;
        \? )
            echo "Invalid argument: -$OPTARG" 1>&2
            exit 1
            ;;
        : )
            interval=${default_interval}
            ;;
    esac
done
shift $((OPTIND -1))

interval=${interval:-$default_interval}

# Call the set_pic function
set_pic
