#!/bin/bash

# Written By Woland

# List PDFs in given directory and opens selection in Evince

#Dependency:
#          dmenu evince 
#          PDFs are assumed to be in ~/Downloads/Document

# https://github.com/wolandark
# https://github.com/wolandark/BASH_Scripts_For_Everyone

# Change to PDFs path
cd $HOME/Downloads/Documents/ || return

# List only the files with .pdf format
# Open selected file in Evince
if book=$(find . -name "*.pdf" | sed 's/\.\///' | dmenu -p 'Library:' -l 15 -fn 'monospace-12' -nb '#282828' -nf '#fbf1c7' -sb '#458588' -sf '#000' -l 20 ); then
  evince "$book"
fi


