#!/bin/bash

servers=(
your.server.com
your.server2.com
)

min_rtt() {
    min_rtt="$(ping -qc4 "$1" | awk -F'[ /]' '/rtt/ {print $7}')"
    printf "%s %s\n" "$min_rtt" "$host"
}

fastest="$(for host in ${servers[@]}; do min_rtt $host; done | sort -V | head -n1)"
fastest_host="${fastest#* }"

echo PASSWORD | doas openconnect $fastest_host:443 --user=USERNAME --passwd-on-stdin

