#!/bin/bash

# Written By Woland

# Change SSH port without editing the config manually

# https://github.com/wolandark
# https://github.com/wolandark/BASH_Scripts_For_Everyone

echo "enter desired port number" 
read port

#uncomment the line containing the word Port
sed -i '/^#.*Port/s/^#//' /etc/ssh/sshd_config

#change port 
sed -i "s/Port\ 22/Port\ $port/g" /etc/ssh/sshd_config

# Restart sshd service
sudo systemctl restart sshd
