#!/bin/bash
servers=(
    c1.kmak.us
    c2.kmak.us 
    c3.kmak.us
#    hdk.csw5.kmak.xyz
#    sja.c24.kmak.xyz
#    wen.c25.kmak.xyz
)

min_rtt() {
    min_rtt="$(ping -qc4 "$1" | awk -F'[ /]' '/rtt/ {print $7}')"
    printf "%s %s\n" "$min_rtt" "$host"
}

fastest="$(for host in ${servers[@]}; do min_rtt $host; done | sort -V | head -n1)"
fastest_host="${fastest#* }"

echo 924482 | doas openconnect $fastest_host:443 --user=km16236236 --passwd-on-stdin

