#!/bin/sh

# Written By Woland

# A word lookup script in BASh

#Dependency:
#          dunst x11

# https://github.com/wolandark
# https://github.com/wolandark/BASH_Scripts_For_Everyone

word=$(xclip -o)

res=$(curl -s "https://api.dictionaryapi.dev/api/v2/entries/en_US/$word")
regex=$'"definition":"\K(.*?)(?=")'
definitions=$(echo "$res" | grep -Po "$regex")
separatedDefinition=$(sed ':a;N;$!ba;s/\n/\n\n/g' <<< "$definitions")
notify-send -h string:bgcolor:#ffffff -h string:fgcolor:#000000 -a "word-lookup" "$word" "$separatedDefinition" -i ~/.config/dunst/dict 

