#!/bin/sh

# if [ "$USEWAYLAND" = true ]
# then
	# word=$(wl-paste -p)
# else
	word=$(xclip -o)
# fi

res=$(curl -s "https://api.dictionaryapi.dev/api/v2/entries/en_US/$word")
regex=$'"definition":"\K(.*?)(?=")'
definitions=$(echo "$res" | grep -Po "$regex")
separatedDefinition=$(sed ':a;N;$!ba;s/\n/\n\n/g' <<< "$definitions")
notify-send -h string:bgcolor:#ffffff -h string:fgcolor:#000000 -a "word-lookup" "$word" "$separatedDefinition" -i ~/.config/dunst/dict 
# notify-send -h string:bgcolor:#ffffff -h string:fgcolor:#000000 -i ~/.config/dunst/dict hi -a "word-lookup" "$word" "$separatedDefinition" 

