#!/bin/bash

# openconnect gui with dmenu

#Dependency:
#          dmenu , openconnect
#          add your servers to the array

servers=("server1.com" "server2.com" "server3.com")

username=$(echo -e "" | dmenu -p "Username:")
password=$(echo -e "" | dmenu -p "Password:")

server=$(printf "%s\n" "${servers[@]}" | dmenu -p "Choose a server:")

echo $password | sudo openconnect $server --user=$username --passwd-on-stdin
