#!/bin/bash

# openconnect tui with fzf

#Dependency:
#          fzf , openconnect
#          add your servers to the array

servers=("server1.com" "server2.com" "server3.com")

username=$(echo "" | fzf --prompt "Username:")
password=$(echo "" | fzf --prompt "Password:")

server=$(printf '%s\n' "${servers[@]}" | fzf --prompt "Choose a server:")

echo $password | sudo openconnect $server --user=$username --passwd-on-stdin
