#!/bin/bash

# Written By Woland

# ping and connect to the fastest openconnect server

#Dependency:
#          openconnect awk/gawk
#          replace PASSWORD and USERNAME with your credentials

# https://github.com/wolandark
# https://github.com/wolandark/BASH_Scripts_For_Everyone

#List of servers to ping
servers=(
your.server.com
your.server2.com
)

min_rtt() {
    min_rtt="$(ping -qc4 "$1" | awk -F'[ /]' '/rtt/ {print $7}')"
    printf "%s %s\n" "$min_rtt" "$host"
}

fastest="$(for host in ${servers[@]}; do min_rtt $host; done | sort -V | head -n1)"
fastest_host="${fastest#* }"

#replace PASSWORD with your password and USERNAME with your username in the line below 
echo PASSWORD | sudo openconnect $fastest_host:443 --user=USERNAME --passwd-on-stdin

