#!/bin/bash

# openconnect gui with rofi

#Dependency:
#          rofi , openconnect
#          add your servers to the array


servers=("server1.com" "server2.com" "server3.com")

username=$(echo "" | rofi -dmenu -p "Username:")
password=$(echo "" | rofi -dmenu -p "Password:" -password)

server=$(echo -e "${servers[@]}" | rofi -dmenu -p "Choose a server:")

echo $password | sudo openconnect $server --user=$username --passwd-on-stdin

