#!/bin/bash

# Written By Woland

# A powermenu using fzf in i3wm. The only thing that is specific to i3wm is the
# logout command. You can replace it with systemd logout command or whatever is
# appropriate for your WM

#Dependency:
#          fzf
#          simply run the script and choose the action

# https://github.com/wolandark
# https://github.com/wolandark/BASH_Scripts_For_Everyone

items="$(echo -e "Shutdown\nReboot\nLogout\nCancel" | fzf --prompt="Choose your fate: " --header-first --reverse --header="POWER MENU" --border=rounded --margin=15% --height 10  --info=hidden)"

case $items in
    Shutdown) 
    sudo poweroff
        ;;
    Reboot)
    sudo reboot
        ;;
    Logout)
        i3-msg exit
        ;;
    *)
        ;;
esac
